[package]
name = "win32-util"
version = "0.2.1-alpha.1"
edition = "2024"
license = "GPL-3.0-only"
description = "High-level idiomatic bindings for a few parts of the Win32 API"
repository = "https://github.com/the0x539/win32-util-rs"
homepage = "https://github.com/the0x539/win32-util-rs"
readme = "README.md"

[package.metadata.docs.rs]
all-features = true
features = ["windows/docs"]
default-target = "x86_64-pc-windows-msvc"
targets = []

[dependencies]
num-rational = { version = "0.4.2", optional = true }
num_enum = { version = "0.7.4", optional = true }
bitflags = { version = "2.9.4", optional = true }

# needed as a direct dependency by #[interface] for some annoying reason
windows-core = { version = "0.62", optional = true }
bilge = { version = "0.3.0", optional = true }

[dependencies.windows]
version = "0.62"

[features]

# windows-rs feature "aliases"/"re-exports"
win-com = ["windows/Win32_System_Com"]
win-ole = ["windows/Win32_System_Ole"]
win-shell = ["windows/Win32_UI_Shell"]
win-variant = ["win-ole", "windows/Win32_System_Variant"]
win-display = ["windows/Win32_Devices_Display"]
win-audio = ["windows/Win32_Media_Audio"]
win-com-storage = ["windows/Win32_System_Com_StructuredStorage"]
win-shell-properties = ["windows/Win32_UI_Shell_PropertiesSystem"]
win-device-properties = ["windows/Win32_Devices_Properties"]
win-wam = ["windows/Win32_UI_WindowsAndMessaging"]
win-gdi = ["windows/Win32_Graphics_Gdi"]
win-registry = ["windows/Win32_System_Registry"]

# actual crate features
com = ["win-com"]
geometry = ["windows/Win32_Foundation"]
desktop-icons = ["com", "win-variant", "win-shell"]
display-config = [
  "geometry",
  "win-display",
  "dep:num-rational",
  "dep:num_enum",
  "dep:bitflags",
]
audio-outputs = [
  "com",
  "dep:windows-core",
  "dep:bitflags",
  "dep:num_enum",
  "win-audio",
  "win-variant",
  "win-com-storage",        # needed for PROPVARIANT
  "win-shell-properties",   # needed for IMMDevice::OpenPropertyStore
  "win-device-properties",
  "windows/Devices_Custom",
]
window-management = [
  "geometry",
  "win-wam",
  "win-gdi",
  "dep:bitflags",
  "dep:num_enum",
  "dep:bilge",
]
registry = ["win-registry", "dep:bitflags"]

[[example]]
name = "query_display_config"
required-features = ["display-config"]

[[example]]
name = "set_display_config"
required-features = ["display-config"]

[[example]]
name = "audio_outputs"
required-features = ["audio-outputs"]

[[example]]
name = "create_window"
required-features = ["window-management"]

[[example]]
name = "registry_watcher"
required-features = ["registry", "desktop-icons"]

[[example]]
name = "audio_output_listener"
required-features = ["audio-outputs"]
