[package]
name = "win32-util"
version = "0.1.0"
edition = "2024"

[dependencies]
num-rational = { version = "0.4.2", optional = true }
num_enum = { version = "0.7.4", optional = true }

[dependencies.windows]
version = "0.62"

[features]

# windows-rs feature "aliases"/"re-exports"
win-com = ["windows/Win32_System_Com"]
win-ole = ["windows/Win32_System_Ole"]
win-shell = ["windows/Win32_UI_Shell"]
win-variant = ["win-ole", "windows/Win32_System_Variant"]
win-display = ["windows/Win32_Devices_Display"]

# actual crate features
com = ["win-com"]
desktop-icons = ["com", "win-variant", "win-shell"]
display-config = ["win-display", "dep:num-rational", "dep:num_enum"]

[[example]]
name = "query_display_config"
required-features = ["display-config"]
